export enum AUTH_ERROR {
  INVALID_SIGN_UP_DATA = 0,
  INVALID_LOGIN_DATA = 1,
  EMAIL_IN_USE = 2,
  USER_NOT_FOUND = 3,
  INVALID_TOKEN = 4,
  SERVER_ERROR = 5,
}

export enum USER_ERROR {
  NOT_ALLOWED = 0,
  INVALID_UPDATE_DATA = 1,
  SERVER_ERROR = 2,
}
